# Generated by Django 3.1.5 on 2021-01-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Description', models.CharField(max_length=100)),
                ('Amount', models.IntegerField(default=0)),
                ('Price', models.DecimalField(decimal_places=10, max_digits=11)),
                ('Image', models.ImageField(upload_to=None)),
                ('Category', models.CharField(max_length=40)),
            ],
        ),
    ]
